language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

env:
  matrix:
    - DJANGO="Django>=1.8,<1.9" # 1.8
    - DJANGO="Django>=1.9,<1.10" # 1.9
    - DJANGO="Django>=1.10,<1.11" # 1.10
    - DJANGO="Django>=1.11,<1.12" # 1.11
    - DJANGO="Django>=2.0,<2.1" # 2.0
    - DJANGO="Django>=2.1,<2.2" # 2.1
    - DJANGO="Django>=2.2,<3.0" # 2.2
    - DJANGO="Django>=3.0,<3.1" # 3.0
    - DJANGO="Django>=3.1,<3.2" # 3.1
    - DJANGO="Django>=3.2,<3.3" # 3.2
    - DJANGO="Django>=4.0,<4.1" # 4.0

cache: pip

install:
  - pip install "$DJANGO" pipenv
  - pip install -r requirements.txt
  - pip install coveralls

matrix:
  exclude:
  - python: "3.5"
    env: DJANGO="Django>=3.0,<3.1" # 3.0

script:
  - coverage run --source=easy manage.py test

after_success:
  coveralls
