language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  matrix:
    - DJANGO="Django<1.6" # 1.5
    - DJANGO="Django<1.7" # 1.6
    - DJANGO="Django<1.8" # 1.7
    - DJANGO="Django<1.9" # 1.8
    - DJANGO="Django<1.10" # 1.9
    - DJANGO="Django<1.11" # 1.10

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install "$DJANGO"
  - pip install -r requirements.txt
  - pip install coveralls

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO="Django<1.6"
    - python: "3.4"
      env: DJANGO="Django<1.7"
    - python: "3.5"
      env: DJANGO="Django<1.6"
    - python: "3.5"
      env: DJANGO="Django<1.7"
    - python: "3.5"
      env: DJANGO="Django<1.8"

script:
  - coverage run --source=easy manage.py test

after_success:
  coveralls